// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbnjjatslxncsmiibyet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibmpqYXRzbHhuY3NtaWlieWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NzQwODEsImV4cCI6MjA1ODU1MDA4MX0.kYKGGglY2K8hu1g13vHXr7kgOfFPPH63zQK9bcprmC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);